name = "Open EGM-4"
description = "Web Interface for EGM-4 Gas Monitor"

[files]
# Map local src directory to virtual file system
"../src" = "./src"
"../README.md" = "./README.md"

packages = [
    "textual",
    "textual-plotext",
    "plotext",
    "pyserial" # We still need this for some type definitions or if code imports it
]
